package garage.webapp.entity;

import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;

/**
 * Created by Aleksander on 05.05.2017.
 */


@Entity
public class Tool {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("/Tool id generated by database")
    private Integer id;

    @Version
    @ApiModelProperty("Generated version number")
    private Integer version;
    @ApiModelProperty("The tool name")
    private String name;
    @ApiModelProperty("The tool description")
    private String description;
    @ApiModelProperty("The tool category, for example electronic, manually etc.")
    private String category;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }
}
